language: python 


matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"

    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.4.3
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.5.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin


before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      brew outdated pyenv || brew upgrade --quiet pyenv;
      brew install homebrew/boneyard/pyenv-pip-rehash;
      brew tap homebrew/science;

      pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      python --version;

      travis_wait 60 brew install pcl;

      if [[ $PYTHON_VERSION = "2.7.10" ]]; then
        # Travis CI Python 2.7 error(numpy)
        # http://d.hatena.ne.jp/aremokoremo/20140507/1399475248
        ls /Library/Python/2.7/site-packages
        # sudo mv /Library/Python/2.7/site-packages/numpy* /Library/Python/2.7/site-packages/temp_bkup/

        travis_wait 60 brew install pcl;
      fi
    fi

  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y;
      sudo apt-get update -y;
      sudo apt-get install libpcl-all -y;
    fi


install:
  - pip install --upgrade pip
  - pip install cython
  - pip install numpy
  - python setup.py build_ext -i
  - python setup.py install


script:
  - python tests/test.py
  - python tests/test_registration.py

