language: python 

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"

    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.4.3
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.5.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin

before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      brew outdated pyenv || brew upgrade --quiet pyenv;
      brew install homebrew/boneyard/pyenv-pip-rehash;
      brew tap homebrew/science;
      brew install pcl --without-apps --without-tools --without-vtk --without-qt;

      pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      python --version;

    fi

  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y;
      sudo apt-get update -y;
      sudo apt-get install libpcl-all -y;
    fi

install:
  - pip install --upgrade pip
  - pip install cython
  - pip install numpy
  - python setup.py build_ext -i
  - python setup.py install

script:
  - python tests/test.py
  - python tests/test_registration.py

