language: python 

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_script:
   - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
   - sudo apt-get update -y
   - sudo apt-get install libpcl-all -y

script: 
    - pip install cython
    - pip install numpy
    - python setup.py build_ext -i
    - python setup.py install

os:
  :linux
  :osx
