language: python 

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_script:
   - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
   - sudo apt-get update
   - sudo apt-get install libpcl-all

script: 
    - pip install cython
    - pip numpy
    - python setup.py install

os:
  :linux
  :osx
